### ISSUE TITLE
FIX add UTF-8 (UTF-32) support

### ISSUE THREAD

**Issue by allanlaal** [captnfab/FireTitle#11] opened 2017-04-26 00:49 UTC
## use case

I use a UTF-32 symbol for a default prefix for all new window titles: 🄵
I open up a new Firefox window

## expected behaviour

window titles get prefixed with 🄵

## actual behaviour

window titles get prefixed with <5 (probably a corrupt version of trying to store a UTF-32 character in latin1 or UTF-8)

**Comment by captnfab** [comment] 2017-04-27 19:24
Hahaha, utf-32! I must admit I never thought of that.
The extension has to be rewritten in the web-extension framework. I have no idea how utf-32 is supported by the API. I'll keep that in mind while writing it. If it's supported, it shouldn't be too hard to implement.

**Comment by captnfab** [comment] 2017-04-27 20:26
Hahaha, utf-32! I must admit I never thought of that.
The extension has to be rewritten in the web-extension framework. I have no idea how utf-32 is supported by the API. I'll keep that in mind while writing it. If it's supported, it shouldn't be too hard to implement.

**Comment by captnfab** [comment] 2017-10-02 14:29
Since XUL version isn't developed anymore, this bug won't be fixed for the old FireTitle add-on.
Any report on the behavior of Crappy's version with utf-32 char is welcomed.

**Comment by captnfab** [comment] 2017-11-13 15:18
I don't have the "<5" problem with Crappy Firetitle, so I guess the problem is solved.
If not, feel free to re-open the bug.

**Closed by captnfab** 2017-11-13 15:18 UTC
